### ISSUE TITLE
Warning: Prop `className` did not match.

### ISSUE THREAD

**Issue by anjananair07** [garronej/tss-react#87]
I'm having difficulty with differences between the client-side and server-side rendering of styles in Material-UI components due to classNames being assigned differently. Below is the error message I'm getting on the console after page load,

![image](https://user-images.githubusercontent.com/103917906/169323642-b862cb6b-cd6f-4043-9150-366981fc751b.png)

The versions I'm using are as follows,

"@emotion/cache": "^11.7.1",
"@emotion/react": "^11.9.0",
"@emotion/server": "^11.4.0",
"@emotion/styled": "^11.8.1",
"@mui/lab": "^5.0.0-alpha.81",
"@mui/material": "^5.7.0",
"react": "^17.0.2",
"tss-react": "^3.6.2",

Please help me solve this issue.

**Comment by garronej** [comment]
Hi @anjananair07,  
Unfortunately I can't help you with the amount of information you provided.  
Do you confirm to have followed the specific instruction for integration with next:  
https://docs.tss-react.dev/ssr/next.js   
You can also have a look at the working example: https://github.com/garronej/tss-react/tree/main/src/test/apps/ssr   

If you are still experiencing problem after that please submit a testable repo where I can reproduce the error.   

Best regards

**Comment by anjananair07** [comment]
Yes, I've followed all the instructions mentioned in the tss-react doc but still no luck.

Is there any way to disable the class prepended to the beginning of every classname i.e. _tss-5tf8fq-MuiHeaderComponent-backButton_ to just _MuiHeaderComponent-backButton_?

I've added the component name to fix this issue as below but still see tss-5tf8fq at the beginning of the className

const useStyles = makeStyles<
  StyleProps,
  | 'logo'
  | 'logoLink'
  | 'backButton'
  | 'slimToolbar'
  | 'navLinks'
  | 'progress'
  | 'profileButton'
>(**{ name: 'MuiHeaderComponent' }**)(
  (theme, { profileHeader, shopHeader }, classes) => ({
    appBar: {
      transition: 'background-color 0.5s ease',
    },
    toolbar: {
      display: 'flex',
      zIndex: zIndexes.header,
      color: theme.palette.common.white,
      padding: theme.spacing(0, 3),
      transition: 'height 0.2s linear',
      [theme.breakpoints.down('sm')]: {
      .......

**Comment by garronej** [comment]
Hi @anjananair07,  
Ok, I think I got it, hold on.

**Comment by garronej** [comment]
It would be much easier if I could see your code, I understand that it's not open source and you can't just share the repo but reverse engineering what you are doing with the few clues you gave me is not an easy task.  

What I can see is that on the server you have:  
<img width="184" alt="image" src="https://user-images.githubusercontent.com/6702424/169545780-a2022756-2d45-4a32-bcee-43784e5a29cb.png">

And on the client:  
<img width="168" alt="image" src="https://user-images.githubusercontent.com/6702424/169545878-c6fa768b-9f38-4823-8d6e-e0af69e6fd8b.png">

The number is a counter that is incremented each time `makeStyles` is invoked.  

In my model I assumed that `createMakeStyles` would be called exactly once for the lifespan of the process and that `makeStyles` would be called a fix amount of time, usually `n` times, `n` being the number of components of your application.  

Currently, it's not what's happening, it's maybe something related with hot reloading.  

Any additional information would be much appreciated.  

Sill investigating...

**Comment by anjananair07** [comment]
Hi @garronej 

I think the issue is with the third parameter (classes) being passed in the makeStyles. The warning is not appearing when I remove the class name that uses classes. 

Please see the code below,

> import {
>   AppBar,
>   CircularProgress,
>   IconButton,
>   ThemeProvider,
>   Toolbar,
>   useMediaQuery,
>   useTheme,
> } from '@mui/material'
> import jwt_decode from 'jwt-decode'
> import mixpanel from 'mixpanel-browser'
> import dynamic from 'next/dynamic'
> import { useRouter } from 'next/router'
> import {
>   FunctionComponent,
>   ReactNode,
>   useContext,
>   useEffect,
>   useRef,
>   useState,
> } from 'react'
> import useScrollTop from 'react-hook-scrolltop'
> import { GlobalStyles } from 'tss-react'
> import { makeStyles } from 'tss-react/mui'
> import { auth } from 'lib/auth'
> import { route } from 'lib/constants'
> import { colors } from 'lib/root'
> import { darkTheme, lightTheme } from 'lib/theme'
> import { isNotFromBostonMarket } from 'lib/utils'
> import zIndexes from 'lib/zIndexes'
> import CartButton from 'components/CartButton'
> import usePatientFetcher from 'components/hooks/usePatientFetcher'
> import useResizeListener from 'components/hooks/useResizeListener'
> import BurgerButton from './BurgerButton'
> import CTAButton from './CTAButton'
> import Link from './Link'
> import Logo from './Logo'
> import { AppContext } from './contexts/AppContext'
> import CloseIcon from './icons/CloseIcon'
> import LeftLongArrow from './icons/LeftLongArrow'
> 
> interface StyleProps {
>   profileHeader: boolean
>   shopHeader: boolean
> }
> 
> const useStyles = makeStyles<
>   StyleProps,
>   | 'logo'
>   | 'logoLink'
>   | 'backButton'
>   | 'slimToolbar'
>   | 'navLinks'
>   | 'progress'
>   | 'profileButton'
> >({ name: 'MuiHeaderComponent' })(
>   (theme, { profileHeader, shopHeader }, classes) => ({
>     appBar: {
>       transition: 'background-color 0.5s ease',
>     },
>     toolbar: {
>       display: 'flex',
>       zIndex: zIndexes.header,
>       color: theme.palette.common.white,
>       padding: theme.spacing(0, 3),
>       transition: 'height 0.2s linear',
>       [theme.breakpoints.down('sm')]: {
>         maxHeight: 72,
>       },
>       [theme.breakpoints.up('md')]: {
>         padding: theme.spacing(0, 8),
>       },
>     },
>     logo: {
>       display: 'flex',
>       zIndex: zIndexes.header,
>       color: colors.tints.grey[4],
>       '& svg': {
>         width: 68,
>         height: 24,
>         fill: 'currentColor',
>       },
>       [theme.breakpoints.up('sm')]: {
>         '& svg': {
>           width: 90,
>           height: 32,
>         },
>       },
>     },
>     logoLink: {
>       '&:hover': {
>         color: colors.primary.blue[0],
>       },
>       '&:active': {
>         color: colors.tints.blue[4],
>       },
>     },
>     backLink: {
>       color: colors.primary.copper[1],
>     },
>     mdUpLinks: {
>       marginLeft: theme.spacing(5),
>       [theme.breakpoints.down('md')]: {
>         display: 'none !important',
>       },
>     },
>     navLinks: {
>       display: 'flex',
>       alignItems: 'center',
>       '& a': {
>         position: 'relative',
>         color: theme.palette.secondary.main,
>         fontSize: 18,
>         fontWeight: 500,
>         '&:hover': {
>           color: colors.primary.blue[0],
>           textDecoration: 'none',
>         },
>         '&:active, &.active': {
>           color: colors.tints.blue[4],
>         },
>       },
>       '& a + a': {
>         paddingLeft: theme.spacing(3),
>       },
>     },
>     actions: {
>       display: 'flex',
>       alignItems: profileHeader || shopHeader ? 'center' : 'auto',
>       marginLeft: 'auto',
>     },
>     profileBook: {
>       height: 40,
>     },
>     loginLink: {
>       paddingRight: theme.spacing(3),
>       [theme.breakpoints.down('md')]: {
>         display: 'none',
>       },
>     },
>     linkWhite: {
>       [theme.breakpoints.up('lg')]: {
>         '&:not(:hover):not(:active)': {
>           color: `${theme.palette.common.white} !important`,
>         },
>       },
>     },
>     bookButton: {
>       padding: theme.spacing(1, 3),
>       zIndex: zIndexes.header,
>       [theme.breakpoints.up('md')]: {
>         padding: theme.spacing(1.5, 2.5),
>       },
>     },
>     menuButton: {
>       zIndex: zIndexes.header,
>       paddingLeft: theme.spacing(2),
>       [theme.breakpoints.up('md')]: {
>         display: 'none',
>       },
>     },
>     profileButton: {
>       color: colors.tints.green[7],
>       border: `1.5px solid ${colors.tints.green[7]}`,
>       marginLeft: theme.spacing(2),
>       fontSize: 13,
>       width: 30,
>       height: 36,
>       borderRadius: 48,
>       padding: 0,
>       lineHeight: 1.5,
>       letterSpacing: '0.06em',
>       fontWeight: 500,
>     },
>     profileButtonDarkTheme: {
>       '& path': {
>         stroke: theme.palette.common.white,
>       },
>     },
>     progress: {
>       position: 'absolute',
>       color: colors.tints.green[7],
>     },
>     slimToolbar: {
>       display: 'grid',
>       zIndex: zIndexes.header,
>       gridTemplateColumns: '1fr 1fr 1fr',
>       borderBottom: `1px solid ${colors.primary.grey[1]}`,
>       color: theme.palette.common.white,
>       padding: theme.spacing(0, 3),
>       transition: 'height 0.2s ease-out',
>       height: 80,
>       [theme.breakpoints.down('sm')]: {
>         maxHeight: 72,
>       },
>       [theme.breakpoints.up('md')]: {
>         padding: theme.spacing(0, 8),
>       },
>     },
>     shopWebView: {
>       paddingTop: theme.spacing(3),
>     },
>     backButton: {
>       width: 48,
>       height: 48,
>       padding: 0,
>       marginLeft: theme.spacing(-1),
>       color: colors.primary.copper[1],
>       '&:hover path': {
>         stroke: colors.tints.blue[4],
>       },
>       '&:active path': {
>         stroke: colors.tints.blue[6],
>       },
>     },
>     slimLogo: {
>       justifyContent: 'center',
>     },
**>     darkTheme: {
>       [`& .${classes.logo}`]: {
>         color: colors.primary.grey[0],
>       },
>       [`& .${classes.logoLink}`]: {
>         '&:hover': {
>           color: theme.palette.common.white,
>         },
>         '&:active': {
>           color: colors.tints.green[4],
>         },
>       },
>       [`& .${classes.backButton}`]: {
>         color: colors.primary.grey[0],
>         '&:hover': {
>           backgroundColor: theme.palette.common.white,
>           borderColor: theme.palette.common.white,
>           color: colors.tints.blue[4],
>           textDecoration: 'none',
>           '& path': {
>             stroke: colors.tints.blue[4],
>           },
>         },
>       },
>       [`& .${classes.slimToolbar}`]: {
>         borderBottomColor: colors.primary.green[2],
>       },
>       [`& .${classes.navLinks}`]: {
>         '& a': {
>           color: colors.primary.grey[0],
>         },
>       },
>       [`& .${classes.progress}`]: {
>         color: colors.primary.grey[0],
>       },
>       [`& .${classes.profileButton}`]: {
>         color: colors.tints.grey[0],
>         borderColor: colors.tints.grey[0],
>       },
>     },**
>     closeButton: {
>       color: theme.palette.common.white,
>       fontSize: 48,
>       zIndex: zIndexes.header,
>       padding: 0,
>     },
>   })
> )
> 
> const MobileMenu = dynamic(() => import('./MobileMenu'))
> 
> interface Props {
>   slim?: boolean
>   useDarkTheme?: boolean
>   backUrl?: string
>   showBackButton?: boolean
>   clickableLogo?: boolean
>   staticPosition?: boolean
>   profileHeader?: boolean
>   shopHeader?: boolean
>   transparent?: boolean
>   children?: ReactNode
>   headerClassName?: string
> }
> 
> const Header: FunctionComponent<Props> = ({
>   slim = false,
>   useDarkTheme = false,
>   showBackButton = false,
>   backUrl = undefined,
>   clickableLogo = true,
>   staticPosition = false,
>   profileHeader = false,
>   shopHeader = false,
>   children = undefined,
>   headerClassName,
> }) => {
>   const {
>     mobileMenuIsShown,
>     toggleMobileMenuIsShown,
>     setHeaderHeight,
>     isWebView,
>   } = useContext(AppContext)
>   const { classes, cx } = useStyles({
>     profileHeader,
>     shopHeader,
>   })
>   const theme = useTheme()
>   const mdUp = useMediaQuery(theme.breakpoints.up('md'))
>   const isTopOfPage = useScrollTop()
>   const router = useRouter()
>   const [email, setEmail] = useState('')
>   const headerRef = useRef<HTMLDivElement>()
>   const { height } = useResizeListener(headerRef)
>   const shopWebView = shopHeader && isWebView
>   useEffect(() => {
>     setHeaderHeight(height)
> 
>     return () => setHeaderHeight(0)
>   }, [height, setHeaderHeight])
> 
>   const isLoggedIn = !!email
> 
>   const { data: patient } = usePatientFetcher()
> 
>   useEffect(() => {
>     const idToken = auth(null, false)
>     const { email } = idToken ? (jwt_decode(idToken) as any) : ''
>     setEmail(email)
>   }, [])
> 
>   const trackingClick = (event: string) => {
>     mixpanel.track(event)
>   }
> 
>   const getInitials = (patient) => {
>     const { display_name, last_name } = patient.person
>     const initials = display_name.charAt(0) + last_name.charAt(0)
>     return initials.toUpperCase()
>   }
> 
>   const isBooking = router.asPath.includes('/booking')
>   const isLoginPage = router.pathname === route.login
>   const showLogin = !isLoggedIn && !isBooking && !isLoginPage
>   const profileIsActive = isLoggedIn && profileHeader
>   const isCheckout =
>     router.asPath.includes('/checkout') && !router.asPath.includes('success')
> 
>   return (
>     <ThemeProvider theme={useDarkTheme ? darkTheme : lightTheme}>
>       <GlobalStyles
>         styles={{
>           body: {
>             overflow: mobileMenuIsShown ? 'hidden' : 'visible',
>           },
>         }}
>       />
>       <AppBar
>         ref={headerRef}
>         position={staticPosition ? 'static' : 'sticky'}
>         color={
>           (!profileIsActive && isTopOfPage && !slim) || staticPosition
>             ? 'transparent'
>             : 'primary'
>         }
>         elevation={0}
>         className={cx(classes.appBar, headerClassName, {
>           [classes.darkTheme]: useDarkTheme,
>           [classes.shopWebView]: shopWebView,
>         })}
>       >
>         {slim ? (
>           <Toolbar className={classes.slimToolbar}>
>             <div>
>               {showBackButton && (
>                 <IconButton
>                   aria-label="back"
>                   className={classes.backButton}
>                   component={Link}
>                   href={backUrl || '/'}
>                   size="large"
>                 >
>                   <LeftLongArrow size="md" />
>                 </IconButton>
>               )}
>             </div>
>             {!isCheckout && (
>               <div className={classes.actions}>
>                 {showLogin && (
>                   <div className={classes.navLinks}>
>                     <Link href={route.login}>Log in</Link>
>                   </div>
>                 )}
>                 {isLoggedIn && (
>                   <IconButton
>                     component={Link}
>                     href={
>                       mdUp ? '/profile/settings/my-info' : '/profile/settings'
>                     }
>                     className={cx(
>                       classes.profileButton,
>                       useDarkTheme && classes.profileButtonDarkTheme
>                     )}
>                     size="large"
>                   >
>                     {patient ? (
>                       getInitials(patient)
>                     ) : (
>                       <CircularProgress
>                         size={20}
>                         className={classes.progress}
>                       />
>                     )}
>                   </IconButton>
>                 )}
>               </div>
>             )}
>           </Toolbar>
>         ) : (
>           <Toolbar
>             className={classes.toolbar}
>             style={{
>               height: staticPosition || isTopOfPage ? 96 : 72,
>             }}
>           >
>             {!profileHeader && !shopHeader && (
>               <nav className={cx(classes.mdUpLinks, classes.navLinks)}>
>                 <Link href="/insurance">Insurance</Link>
>                 <Link href="/studios">Locations</Link>
>                 <Link href="/services">Services</Link>
>                 <Link href="/careers">Careers</Link>
>                 <Link href="/shop">Shop</Link>
>               </nav>
>             )}
>             {profileHeader && (
>               <nav className={cx(classes.mdUpLinks, classes.navLinks)}>
>                 <Link href="/profile">Home</Link>
>                 <Link href="/profile/health">My Mouth</Link>
>                 <Link href="/profile/appointments">Visits</Link>
>                 <Link
>                   href="/shop"
>                   onClick={() => trackingClick('Profile Shop Selected')}
>                 >
>                   Shop
>                 </Link>
>                 {patient && isNotFromBostonMarket(patient) && (
>                   <Link
>                     href="/profile/invite-a-friend"
>                     onClick={() =>
>                       trackingClick('Profile Invite A Friend Selected')
>                     }
>                   >
>                     Invite a Friend
>                   </Link>
>                 )}
>               </nav>
>             )}
>             <div className={classes.actions}>
>               {!shopHeader &&
>                 (!profileHeader || (profileHeader && !isLoggedIn)) && (
>                   <div className={classes.navLinks}>
>                     <Link
>                       href={isLoggedIn ? '/profile' : route.login}
>                       className={cx(classes.loginLink, {
>                         [classes.linkWhite]:
>                           router.pathname === '/' && isTopOfPage,
>                       })}
>                     >
>                       {isLoggedIn ? 'My Profile' : 'Log in'}
>                     </Link>
>                   </div>
>                 )}
>               <ThemeProvider
>                 theme={
>                   mobileMenuIsShown || useDarkTheme ? darkTheme : lightTheme
>                 }
>               >
>                 {!shopHeader && (
>                   <CTAButton
>                     className={cx(classes.bookButton, {
>                       [classes.profileBook]: profileHeader,
>                     })}
>                     id="header-book-button"
>                   >
>                     {!mdUp || profileHeader ? 'Book' : 'Book Now'}
>                   </CTAButton>
>                 )}
>                 {shopHeader && (
>                   <CartButton
>                     useDarkTheme={useDarkTheme}
>                     id="header-cart-icon"
>                   />
>                 )}
>                 {isLoggedIn &&
>                   !isWebView &&
>                   (profileHeader || shopHeader) &&
>                   !mobileMenuIsShown && (
>                     <IconButton
>                       component={mdUp ? Link : undefined}
>                       href={mdUp ? '/profile/settings/my-info' : undefined}
>                       onClick={mdUp ? undefined : toggleMobileMenuIsShown}
>                       edge="end"
>                       aria-label="profile settings button"
>                       id="header-profile-button"
>                       className={classes.profileButton}
>                       size="large"
>                     >
>                       {patient ? (
>                         getInitials(patient)
>                       ) : (
>                         <CircularProgress
>                           size={20}
>                           className={classes.progress}
>                         />
>                       )}
>                     </IconButton>
>                   )}
>                 {!profileIsActive && !shopHeader && (
>                   <BurgerButton
>                     className={classes.menuButton}
>                     aria-label="menu"
>                     onClick={toggleMobileMenuIsShown}
>                     active={mobileMenuIsShown}
>                     width={20}
>                     color={
>                       mobileMenuIsShown || useDarkTheme
>                         ? theme.palette.common.white
>                         : colors.primary.copper[1]
>                     }
>                     lineHeight={2}
>                     lineSpacing={3}
>                     padding="0"
>                   />
>                 )}
>                 {mobileMenuIsShown && (
>                   <>
>                     {profileIsActive && (
>                       <IconButton
>                         onClick={toggleMobileMenuIsShown}
>                         edge="end"
>                         className={classes.closeButton}
>                         size="large"
>                       >
>                         <CloseIcon color="inherit" fontSize="inherit" />
>                       </IconButton>
>                     )}
>                     <MobileMenu
>                       isLoggedIn={isLoggedIn}
>                       profileHeader={profileHeader}
>                     />
>                   </>
>                 )}
>               </ThemeProvider>
>             </div>
>           </Toolbar>
>         )}
>         {children}
>       </AppBar>
>     </ThemeProvider>
>   )
> }
> 
> export default Header
> 

Thank you.

**Comment by garronej** [comment]
Hi @anjananair07,  
Thank you for the code snippet.  
I have identified what is the source of the problem, it is indeed related to `classes`.  
The problem is that the fix is very tricky to implement and I don't understand exactly how you end up in this situation.  
Does your project contains 2000 component (2000 different call to `makeStyles`), if not, how comes, on the server `makeStyles` is invoked thousand of times.  
What version of Next, React, react-dom, emotion are you using?  
It would really help me if you could come up with a repo where I can reproduce the problem.  

If you can do that I will try to solve the issue in the best delay.  
Otherwise I will wait and see if other peoples report the same issue.  

Best regards,

**Comment by anjananair07** [comment]
Hi @garronej 

Thank you for your prompt reply!

There are around 300 components in my project and the issue occurred when we upgraded to MUI v5 and react-tss.

Next version: 12.1.6

**Comment by garronej** [comment]
Ok thank you,  
I'll need a repoduction path.  
Try to clone your project, remove the sensible part and share it with me?

**Comment by garronej** [comment]
Can you try with 
```json
"tss-react": "v3.7.0-beta.2"
```  

And copy paste what you get in the log.  

Thank you

**Comment by anjananair07** [comment]
Sure @garronej

**Comment by anjananair07** [comment]
Hi @garronej 

Please find the screenshot of the Dev console below,

![image](https://user-images.githubusercontent.com/103917906/169818172-6c5222e5-7d0e-492c-a1da-580afa603e41.png)

Thanks.

**Comment by garronej** [comment]
> Could you try building the app and see if you have the same problem in production (yarn build && yarn serve)?  

Before upgrading, please check if the issue is only in dev mode or if it happens in production as well.  

Then you can try with:   
```json
"tss-react": "v3.7.0-beta.3"
```  
It should fix the issue.

**Comment by anjananair07** [comment]
The issue is only in dev mode and not in production. 

Below is the o/p of terminal,
![image](https://user-images.githubusercontent.com/103917906/169855381-f8c401f9-b5a5-463f-90bf-7cbffd586042.png)


Still see warning message after upgrading (v3.7.0-beta.3),

![image](https://user-images.githubusercontent.com/103917906/169854978-b348e22a-01c1-4261-87d5-f52ff25787c5.png)

**Comment by garronej** [comment]
Thank you for the additional info but please please, would you share a reproducible repo.  
I spent many hours already trying unsuccessfully to reproduce the bug.  
It's super hard to debug without knowing exactly what is going on.

**Comment by garronej** [comment]
Could you please try with?  
```json
        "next": "12.1.7-canary.4",
        "react": "18.1.0",
        "react-dom": "18.1.0",
       "tss-react": "3.6.2"
```

**Comment by anjananair07** [comment]
Thank you so much for spending your time helping me!

The issue still persists with the version you have mentioned above :(
Yes, I'll try to share a reproducible repo as soon as possible.

**Comment by garronej** [comment]
@anjananair07 you are welcome,  
But you know, I am pretty sure your issue is legit bug on `tss-react` end, it had to be addressed.  

Be sure that, one war on another, I will publish a patch that fixes the issue.  
I just hope I'll find a way to fix it that is transparent for you.

**Comment by anjananair07** [comment]
Works like a charm! 
Thank you so much @garronej
